### PR TITLE
Update to new USWDS theme

### PR DESCRIPTION
**Pull request by shawndwells**

### CODE REVIEW

**Comment by shawndwells** [comment]
@redhatrises this should update to the latest USWDS. Comes at a cost of adding some things we don't need, that will need to be stripped out in future PRs.

**Comment by redhatrises** [comment]
This PR breaks the github pages deployment due to jekyll version 4 and greater not being supported in github-pages. I would recommend either using the original theme or downgrade to uswds-jekyll v4.2.0

**Comment by redhatrises** [comment]
Actually.... may have found a workaround.

**Comment by shawndwells** [comment]
> This PR breaks the github pages deployment due to jekyll version 4 and greater not being supported in github-pages. I would recommend either using the original theme or downgrade to uswds-jekyll v4.2.0

Looks to be working? 
https://shawndwells.github.io/Open-Source-Policy/

**Pull request merged**
