### PR TITLE
Adding sample CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by jshcodes**

### CODE REVIEW

**Review by shawndwells — COMMENTED** [review]
@redhatrises Hey Gabe - you had some ideas on how to use these templates to cascade into other CRWD projects. Can you describe that again?

**Comment by redhatrises** [comment]
> @redhatrises Hey Gabe - you had some ideas on how to use these templates to cascade into other CRWD projects. Can you describe that again?

Basically, the idea is to point through a link in the README to the CODE_OF_CONDUCT.md in this project rather than maintaining in everyone's own repo... but also have some sort of way for creating your own CODE_OF_CONDUCT if needed for some reason.

**Comment by shawndwells** [comment]
Ah, that makes sense. "Look over there!" and link to this.

**Review by shawndwells — APPROVED** [review]
We can merge this in now, and work incrementally for it to become a place for all CrowdStrike GitHub org projects to point back to (vs having to keep their own copies).

**Pull request merged**
